### ISSUE TITLE
Failed to train the model

### ISSUE THREAD

**Issue by Fqlox** [adityabingi/DCGAN#2]
Hello,

I wanted to launch a training on a custom dataset. And I got this error : 

`At Epoch 1
.........................................
2020-07-28 21:32:20.295784: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Not found: NewRandomAccessFile failed to Create/Open: tfrecords/train.tfrecord : Le fichier spÚcifiÚ est introuvable.
; No such file or directory
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
Traceback (most recent call last):
  File "dcgan.py", line 192, in <module>
    main()
  File "dcgan.py", line 186, in main
    train(strategy, restore=False)
  File "dcgan.py", line 156, in train
    dcgan.train_loop(Config.num_epochs, dist_dataset, dist_noise_dataset)
  File "dcgan.py", line 121, in train_loop
    for one_batch in dist_dataset:
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 275, in __next__
    return self.get_next()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 292, in get_next
    self._iterators[i].get_next_as_list_deprecated(new_name))
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 842, in get_next_as_list_deprecated
    data_list = self._iterator.get_next()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\multi_device_iterator_ops.py", line 332, in get_next
    result.append(self._device_iterators[i].get_next())
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 737, in get_next
    return self._next_internal()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2659, in iterator_get_next_sync
    "output_types", output_types, "output_shapes", output_shapes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 83: invalid continuation byte
`

note that "Le fichier spÚcifiÚ est introuvable" means it couldnt find a file. 

I modified the config file and I created a "tfrecords" directory

I'm on windows 10, with python 3.6 and tensorflow 2.0.0 and using a RTX 2070.

Thanks in advance

**Comment by adityabingi** [comment]
Code in dcgan.py supports multigpu training however to train on single GPU change 
strategy = tf.distribute.MirroredStrategy(devices)(line 185) to strategy = tf.distribute.OneDeviceStrategy(devices)
Then try running the training job and let me know

**Comment by Fqlox** [comment]
> Code in dcgan.py supports multigpu training however to train on single GPU change
> strategy = tf.distribute.MirroredStrategy(devices)(line 185) to strategy = tf.distribute.OneDeviceStrategy(devices)
> Then try running the training job and let me know

Thanks for your quick answer, I modified the strategy to single gpu and got :

`Traceback (most recent call last):
  File "dcgan.py", line 194, in <module>
    main()
  File "dcgan.py", line 186, in main
    strategy = tf.distribute.OneDeviceStrategy(devices)
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\one_device_strategy.py", line 80, in __init__
    super(OneDeviceStrategy, self).__init__(OneDeviceExtended(self, device))
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\one_device_strategy.py", line 250, in __init__
    self._device = device_util.canonicalize(device)
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\device_util.py", line 47, in canonicalize
    d = tf_device.DeviceSpec.from_string(d)
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\framework\device_spec.py", line 138, in from_string
    return cls(*cls._string_to_components(spec))
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\framework\device_spec.py", line 293, in _string_to_components
    cached_result = _STRING_TO_COMPONENTS_CACHE.get(spec)
TypeError: unhashable type: 'list'
`


I also tried `strategy = tf.distribute.OneDeviceStrategy('/device:GPU:0')`  which did not work well.

**Comment by adityabingi** [comment]
Sorry, I forgot to mention tf.distribute.OneDeviceStrategy accepts device id as a string, not as a list.
So strategy = tf.distribute.OneDeviceStrategy('/device:GPU:0') should work fine. 

Also, you can train on Single GPU by directly setting num_gpu = 1  in config.py even with tf.distributed.MirrorStrategy, nothing needs to be changed in dcgan.py

I ran single-gpu training with both strategies, and it works fine. If you still run into errors;
Check whether your tensorflow installation can load gpus with:
>>> import tensorflow as tf
>>> tf.test.is_gpu_available()

It should return True

Also, check whether your installation follows the tested build configurations [here](https://www.tensorflow.org/install/source#linux)

**Comment by Fqlox** [comment]
I already tried to set up num_gpu = 1. 
My Tensorflow installation looks fine : it returned true.   
Although I still got the same error :

`At Epoch 1
.........................................
2020-07-31 11:11:07.543247: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Not found: NewRandomAccessFile failed to Create/Open: records/train.tfrecord : Le fichier spÚcifiÚ est introuvable.
; No such file or directory
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
Traceback (most recent call last):
  File "dcgan.py", line 194, in <module>
    main()
  File "dcgan.py", line 188, in main
    train(strategy, restore=False)
  File "dcgan.py", line 156, in train
    dcgan.train_loop(Config.num_epochs, dist_dataset, dist_noise_dataset)
  File "dcgan.py", line 121, in train_loop
    for one_batch in dist_dataset:
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 275, in __next__
    return self.get_next()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 292, in get_next
    self._iterators[i].get_next_as_list_deprecated(new_name))
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\distribute\input_lib.py", line 842, in get_next_as_list_deprecated
    data_list = self._iterator.get_next()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\multi_device_iterator_ops.py", line 332, in get_next
    result.append(self._device_iterators[i].get_next())
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 737, in get_next
    return self._next_internal()
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "D:\Program Files (x86)\Anaconda\envs\dcgan2\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2659, in iterator_get_next_sync
    "output_types", output_types, "output_shapes", output_shapes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 81: invalid continuation byte`

**Comment by adityabingi** [comment]
You seem to have a problem with tfrecord file. 
'utf-8' codec can't decode byte 0xe9 in position 81: invalid continuation byte; this generally occurs when you are trying to read a binary file using text decoder like 'utf-8'.
Did you create tfrecords using the dataset.py..? Check whether your tfrecord file is created properly.

**Comment by Fqlox** [comment]
I recreated the tfrecords and it changed the issue :


`2020-08-03 12:37:18.955413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6306 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:09:00.0, compute capability: 7.5)
At Epoch 1
.........................................
2020-08-03 12:37:30.851706: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-08-03 12:37:31.973408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-03 12:42:36.487510: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-08-03 12:42:36.576464: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-08-03 12:42:36.731566: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Discriminator/conv2d/Conv2D}}]]
         [[Identity_3/_4]]
2020-08-03 12:42:36.783867: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Discriminator/conv2d/Conv2D}}]]
2020-08-03 12:42:37.220222: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-08-03 12:42:37.235062: W .\tensorflow/stream_executor/stream.h:2003] attempting to perform DNN operation using StreamExecutor without DNN support
2020-08-03 12:42:38.775973: I tensorflow/stream_executor/stream.cc:1868] [stream=00000171457D7E90,impl=000001714CA32840] did not wait for [stream=00000171457D7F90,impl=000001714CA32990]
2020-08-03 12:42:38.780584: I tensorflow/stream_executor/stream.cc:4816] [stream=00000171457D7E90,impl=000001714CA32840] did not memcpy host-to-device; source: 000001712FEDEB00
2020-08-03 12:42:38.798355: F tensorflow/core/common_runtime/gpu/gpu_util.cc:342] CPU->GPU Memcpy failed`


It looks like a problem with the cuDNN installation although It worked on various other projects and my installation of Tensorflow can have acess to the GPU

`>>> tf.test.is_gpu_available()
2020-08-03 16:04:49.182547: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-08-03 16:04:49.204816: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-08-03 16:04:49.250972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.74
pciBusID: 0000:09:00.0
2020-08-03 16:04:49.256942: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-08-03 16:04:49.263471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-08-03 16:04:57.126219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-03 16:04:57.129808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-08-03 16:04:57.132190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-08-03 16:04:57.147941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6306 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:09:00.0, compute capability: 7.5)
True`

**Comment by adityabingi** [comment]
Loaded runtime CuDNN library: 7.1.4 but source was compiled with: 7.6.0; 
this happens when you have multiple versions of Cuda installed on your system and your environment is loading the wrong version. To fix this check out this [issue](https://github.com/tensorflow/tensorflow/issues/23715#issuecomment-454206467)

**Comment by Fqlox** [comment]
Thanks for your answer I modified the cudnn file within the Anaconda package and I also tried to use `conda install -c anaconda cudnn` but both still give me the same error

**Comment by adityabingi** [comment]
Remove all your Cuda installations, tensorflow and reinstall everything following tensorflow tested configurations.

Also, closing this issue as your issue is with tensorflow installation. Reopen it if you have any error related to the specifics of model training
